"""Ponto unico de import dos models.

Importar este modulo registra todas as tabelas no metadata do Alembic e
garante que seed/services enxerguem o schema completo.
"""
from .arena import Arena
from .booking import (
    ACTIVE_STATUSES,
    PLAN_AVULSO,
    PLAN_MENSALISTA,
    STATUS_CANCELLED,
    STATUS_COMPLETED,
    STATUS_CONFIRMED,
    STATUS_EXPIRED,
    STATUS_PAYMENT_CONFIRMED,
    STATUS_PAYMENT_FAILED,
    STATUS_PENDING_PAYMENT,
    STATUS_REFUNDED,
    STATUS_REJECTED,
    STATUS_REQUESTED,
    Booking,
    BookingStatusEvent,
)
from .court import Court, CourtBlock, CourtRecurringAvailability
from .favorite import UserFavorite
from .message import (
    CONVERSATION_ACTIVE,
    CONVERSATION_ARCHIVED,
    CONVERSATION_KIND_ARENA,
    MESSAGE_TYPE_TEXT,
    Conversation,
    ConversationParticipant,
    Message,
)
from .notification import (
    NOTIF_BOOKING_APPROVED,
    NOTIF_BOOKING_CANCELLED,
    NOTIF_BOOKING_COMPLETED,
    NOTIF_BOOKING_EXPIRED,
    NOTIF_BOOKING_REJECTED,
    NOTIF_MESSAGE_NEW,
    NOTIF_PAYMENT_CONFIRMED,
    PUSH_STATUS_ERRORED,
    PUSH_STATUS_OK,
    Notification,
    PushLog,
    UserDevice,
)
from .payment import (
    PAYMENT_CONFIRMED,
    PAYMENT_FAILED,
    PAYMENT_PENDING,
    PAYMENT_REFUNDED,
    Payment,
)
from .review import Review
from .user import (
    PROVIDER_GOOGLE,
    PROVIDER_PASSWORD,
    ROLE_ADMIN,
    ROLE_GERENTE,
    ROLE_JOGADOR,
    User,
)
from .user_session import UserSession

__all__ = [
    "User",
    "UserSession",
    "Arena",
    "Court",
    "CourtBlock",
    "CourtRecurringAvailability",
    "Review",
    "UserFavorite",
    "Booking",
    "BookingStatusEvent",
    "Conversation",
    "ConversationParticipant",
    "Message",
    "CONVERSATION_KIND_ARENA",
    "CONVERSATION_ACTIVE",
    "CONVERSATION_ARCHIVED",
    "MESSAGE_TYPE_TEXT",
    "Payment",
    "PAYMENT_PENDING",
    "PAYMENT_CONFIRMED",
    "PAYMENT_FAILED",
    "PAYMENT_REFUNDED",
    "Notification",
    "UserDevice",
    "PushLog",
    "NOTIF_PAYMENT_CONFIRMED",
    "NOTIF_BOOKING_APPROVED",
    "NOTIF_BOOKING_REJECTED",
    "NOTIF_BOOKING_CANCELLED",
    "NOTIF_BOOKING_COMPLETED",
    "NOTIF_BOOKING_EXPIRED",
    "NOTIF_MESSAGE_NEW",
    "PUSH_STATUS_OK",
    "PUSH_STATUS_ERRORED",
    "PLAN_AVULSO",
    "PLAN_MENSALISTA",
    "STATUS_PENDING_PAYMENT",
    "STATUS_PAYMENT_CONFIRMED",
    "STATUS_REQUESTED",
    "STATUS_CONFIRMED",
    "STATUS_COMPLETED",
    "STATUS_PAYMENT_FAILED",
    "STATUS_REJECTED",
    "STATUS_CANCELLED",
    "STATUS_EXPIRED",
    "STATUS_REFUNDED",
    "ACTIVE_STATUSES",
    "ROLE_JOGADOR",
    "ROLE_GERENTE",
    "ROLE_ADMIN",
    "PROVIDER_PASSWORD",
    "PROVIDER_GOOGLE",
]