"""Ponto unico de import dos models.

Importar este modulo registra todas as tabelas no metadata do Alembic e
garante que seed/services enxerguem o schema completo.
"""
from .admin import (
    ADMIN_ACTION_ARENA_PAUSE,
    ADMIN_ACTION_ARENA_REACTIVATE,
    AdminAction,
)
from .arena import Arena
from .booking import (
    ACTIVE_STATUSES,
    PLAN_AVULSO,
    PLAN_MENSALISTA,
    STATUS_CANCELLED,
    STATUS_COMPLETED,
    STATUS_CONFIRMED,
    STATUS_EXPIRED,
    STATUS_PAYMENT_CONFIRMED,
    STATUS_PAYMENT_FAILED,
    STATUS_PENDING_PAYMENT,
    STATUS_REFUNDED,
    STATUS_REJECTED,
    STATUS_REQUESTED,
    Booking,
    BookingStatusEvent,
)
from .club import (
    CLUB_CODE_ALPHABET,
    CLUB_CODE_LENGTH,
    CLUB_ROLE_DONO,
    CLUB_ROLE_MEMBRO,
    Club,
    ClubMember,
    ClubMessage,
)
from .coupon import Coupon
from .court import Court, CourtBlock, CourtRecurringAvailability
from .favorite import UserFavorite
from .match import (
    MATCH_EVENT_GOAL,
    MATCH_EVENT_RED,
    MATCH_EVENT_TYPES,
    MATCH_EVENT_YELLOW,
    MATCH_PHASE_DURING_GAME,
    MATCH_PHASE_POST_GAME,
    MATCH_PHASE_PRE_GAME,
    MATCH_STATUS_ENDED,
    MATCH_STATUS_LIVE,
    MATCH_STATUS_SCHEDULED,
    Match,
    MatchEvent,
    MatchMedia,
    MatchPlayer,
    MatchTeam,
)
from .message import (
    CONVERSATION_ACTIVE,
    CONVERSATION_ARCHIVED,
    CONVERSATION_KIND_ARENA,
    MESSAGE_TYPE_TEXT,
    Conversation,
    ConversationParticipant,
    Message,
)
from .notification import (
    NOTIF_BOOKING_APPROVED,
    NOTIF_BOOKING_CANCELLED,
    NOTIF_BOOKING_COMPLETED,
    NOTIF_BOOKING_EXPIRED,
    NOTIF_BOOKING_REJECTED,
    NOTIF_CLUBE_ENTROU,
    NOTIF_MESSAGE_NEW,
    NOTIF_PARTIDA_ATRASO,
    NOTIF_PARTIDA_ENCERRADA,
    NOTIF_PARTIDA_PRESENCA,
    NOTIF_PAYMENT_CONFIRMED,
    NOTIF_PELADA_CRIADA,
    NOTIF_PELADA_PRESENCA,
    PUSH_STATUS_ERRORED,
    PUSH_STATUS_OK,
    Notification,
    PushLog,
    UserDevice,
)
from .payment import (
    PAYMENT_CONFIRMED,
    PAYMENT_FAILED,
    PAYMENT_PENDING,
    PAYMENT_REFUNDED,
    Payment,
)
from .pelada import (
    ATTENDANCE_NAO,
    ATTENDANCE_SIM,
    ATTENDANCE_TALVEZ,
    ATTENDANCE_VALUES,
    PELADA_KIND_AVULSA,
    PELADA_KIND_CLUBE,
    PELADA_STATUS_AGENDADA,
    PELADA_STATUS_CANCELADA,
    PELADA_STATUS_CONCLUIDA,
    Pelada,
    PeladaAttendance,
)
from .review import Review
from .settlement import SETTLEMENT_FAILED, SETTLEMENT_PAID, SETTLEMENT_PENDING, Settlement
from .user import (
    PROVIDER_GOOGLE,
    PROVIDER_PASSWORD,
    ROLE_ADMIN,
    ROLE_GERENTE,
    ROLE_JOGADOR,
    User,
)
from .user_session import UserSession

__all__ = [
    "User",
    "UserSession",
    "Arena",
    "AdminAction",
    "ADMIN_ACTION_ARENA_PAUSE",
    "ADMIN_ACTION_ARENA_REACTIVATE",
    "Court",
    "CourtBlock",
    "CourtRecurringAvailability",
    "Review",
    "UserFavorite",
    "Coupon",
    "Settlement",
    "SETTLEMENT_PENDING",
    "SETTLEMENT_PAID",
    "SETTLEMENT_FAILED",
    "Booking",
    "BookingStatusEvent",
    "Conversation",
    "ConversationParticipant",
    "Message",
    "CONVERSATION_KIND_ARENA",
    "CONVERSATION_ACTIVE",
    "CONVERSATION_ARCHIVED",
    "MESSAGE_TYPE_TEXT",
    "Payment",
    "PAYMENT_PENDING",
    "PAYMENT_CONFIRMED",
    "PAYMENT_FAILED",
    "PAYMENT_REFUNDED",
    "Notification",
    "UserDevice",
    "PushLog",
    "NOTIF_PAYMENT_CONFIRMED",
    "NOTIF_BOOKING_APPROVED",
    "NOTIF_BOOKING_REJECTED",
    "NOTIF_BOOKING_CANCELLED",
    "NOTIF_BOOKING_COMPLETED",
    "NOTIF_BOOKING_EXPIRED",
    "NOTIF_MESSAGE_NEW",
    "NOTIF_CLUBE_ENTROU",
    "NOTIF_PELADA_CRIADA",
    "NOTIF_PELADA_PRESENCA",
    "NOTIF_PARTIDA_PRESENCA",
    "NOTIF_PARTIDA_ATRASO",
    "NOTIF_PARTIDA_ENCERRADA",
    "PUSH_STATUS_OK",
    "PUSH_STATUS_ERRORED",
    "PLAN_AVULSO",
    "PLAN_MENSALISTA",
    "STATUS_PENDING_PAYMENT",
    "STATUS_PAYMENT_CONFIRMED",
    "STATUS_REQUESTED",
    "STATUS_CONFIRMED",
    "STATUS_COMPLETED",
    "STATUS_PAYMENT_FAILED",
    "STATUS_REJECTED",
    "STATUS_CANCELLED",
    "STATUS_EXPIRED",
    "STATUS_REFUNDED",
    "ACTIVE_STATUSES",
    "ROLE_JOGADOR",
    "ROLE_GERENTE",
    "ROLE_ADMIN",
    "PROVIDER_PASSWORD",
    "PROVIDER_GOOGLE",
    "Club",
    "ClubMember",
    "ClubMessage",
    "CLUB_ROLE_DONO",
    "CLUB_ROLE_MEMBRO",
    "CLUB_CODE_ALPHABET",
    "CLUB_CODE_LENGTH",
    "Pelada",
    "PeladaAttendance",
    "PELADA_KIND_CLUBE",
    "PELADA_KIND_AVULSA",
    "PELADA_STATUS_AGENDADA",
    "PELADA_STATUS_CANCELADA",
    "PELADA_STATUS_CONCLUIDA",
    "ATTENDANCE_SIM",
    "ATTENDANCE_TALVEZ",
    "ATTENDANCE_NAO",
    "ATTENDANCE_VALUES",
    "Match",
    "MatchTeam",
    "MatchPlayer",
    "MatchEvent",
    "MatchMedia",
    "MATCH_STATUS_SCHEDULED",
    "MATCH_STATUS_LIVE",
    "MATCH_STATUS_ENDED",
    "MATCH_PHASE_PRE_GAME",
    "MATCH_PHASE_DURING_GAME",
    "MATCH_PHASE_POST_GAME",
    "MATCH_EVENT_GOAL",
    "MATCH_EVENT_YELLOW",
    "MATCH_EVENT_RED",
    "MATCH_EVENT_TYPES",
]